version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gocritic
    - revive
    - depguard
    - bodyclose
    - prealloc
    - gocognit
    - gocyclo
    - dupl
    - nakedret
    - unconvert
    - ineffassign
    - asciicheck
    - nolintlint
  disable:
    - depguard
    - gocognit


issues:
  max-issues-per-linter: 0
  max-same-issues: 0


