name: CI Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24' 

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Run linting
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: latest

      # Run unit tests with improved output
      - name: Run unit tests
        run: |
          go test ./... -v

      # Install staticcheck
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      # Run static code analysis 
      - name: Run staticcheck
        run: staticcheck ./...
